
services:
  kafka-server-1:
    image: bitnami/kafka:4.0.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=R3FPWW78RfmMvIyzCvg4uw
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-server-1:9091,2@kafka-server-2:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server-1:9090,EXTERNAL://kafka-server-1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - /bitnami/kafka/server-1-logs
  kafka-server-2:
    image: bitnami/kafka:4.0.0
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=R3FPWW78RfmMvIyzCvg4uw
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-server-1:9091,2@kafka-server-2:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server-2:9090,EXTERNAL://kafka-server-2:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - /bitnami/kafka/server-2-logs
  arm_hunter_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=arm_hunter_db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
  usermicroservice:
    restart: always
    build: usermicroservice/.
    depends_on:
      - arm_hunter_db
      - kafka-server-1
      - kafka-server-2
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://arm_hunter_db:5432/arm_hunter_db'
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 'postgres'
  resumemicroservice:
    restart: always
    build: resumemicroservice/.
    depends_on:
      - arm_hunter_db
      - kafka-server-1
      - kafka-server-2
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://arm_hunter_db:5432/arm_hunter_db'
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 'postgres'
  apimicroservice:
    restart: always
    build: apimicroservice/.
    depends_on:
      - kafka-server-1
      - kafka-server-2
    ports:
      - "8080:8080"